version: "3"
services:
  sphere:
    image: miguelpeixe/sphereserver
    restart: unless-stopped
    ports:
      - "${SHARD_PORT}:2593"
    environment:
      - SHARD_NAME
      - SHARD_EMAIL
      - SHARD_URL
      - REST_API_PUBLIC_API
      - ENABLE_MYSQL
      - MYSQL_SERVER
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - ${CONFIG}:/config
      - ${DATA}/accounts:/data/accounts
      - ${DATA}/logs:/data/logs
      - ${DATA}/save:/data/save
    networks:
      sphere:
  mysql:
    image: mysql:5
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    networks:
      sphere:
        aliases:
          - ${MYSQL_SERVER}

networks:
  sphere:
