#!/usr/bin/with-contenv bash

cd /etc/sphere

mkfifo /tmp/sphere-input
cat > /tmp/sphere-input &

tail -f /tmp/sphere-input | \
  script --return -c "/etc/sphere/spheresvr" /dev/null | \
  tee /tmp/sphere-output

tail -0f /tmp/sphere-output
